name = "Immersion Cigs"
author = "Rebel / Facel / Panimala"
url = "https://github.com/rebelvg/immersion_cigs"
prefix = "klpq"
mainprefix = "murshun_cigs"

[files]
include = [
    "mod.cpp",
    "cigs.paa"
]
exclude = [
  "README.md"
]

[version]
major = 1
minor = 5
patch = 2
build = 0
git_hash = 0